### ISSUE TITLE
What's the build command?

### ISSUE THREAD

**Issue by bnomis** [swannodette/om-next-demo#1]
I'd really like to build this project so I can put some printlns in to see what is going on. But I can't figure out the build command. Thanks.

**Comment by ProjectFrank** [comment]
+1

**Comment by SMeister** [comment]
Inside the todomvc directory, run
>> lein run -m clojure.main script/build.clj
to build the js.

Now open a repl (>> lein repl) and start the server:
(use 'todomvc.system)
(def sys
  (dev-system
    {:db-uri   "datomic:mem://localhost:4334/todos"
    :web-port 8081}))
(com.stuartsierra.component/start sys)

**Comment by dmitrig01** [comment]
:+1:

**Comment by SMeister** [comment]
Create a new file "figwheel.clj" inside of todomvc/script with the following contents:

```clojure
(require
  '[figwheel-sidecar.repl-api :as ra]
  '[com.stuartsierra.component :as component]
  '[todomvc.system :as system])

(def figwheel-config
  {:figwheel-options {}
   :build-ids ["dev"]
   :all-builds
   [{:id "dev"
     :figwheel true
     :source-paths ["src/cljs"]
     :compiler {:main 'todomvc.core
                :asset-path "/js"
                :output-to "resources/public/js/app.js"
                :output-dir "resources/public/js"
                :optimizations :none
                :static-fns true
                :optimize-constants true
                :pretty-print true
                :externs ["src/js/externs.js"]
                :closure-defines '{goog.DEBUG true}
                :verbose true}}]})

(defrecord Figwheel []
  component/Lifecycle
  (start [config]
    (ra/start-figwheel! config)
    config)
  (stop [config]
    (ra/stop-figwheel!)
    config))

(def sys
  (atom
    (component/system-map
      :figwheel (map->Figwheel figwheel-config)
      :app-server (system/dev-system
                    {:db-uri   "datomic:mem://localhost:4334/todos"
                     :web-port 8081}))))

(defn start []
  (swap! sys component/start))

(defn stop []
  (swap! sys component/stop))

(defn reload []
  (stop)
  (start))

(defn repl []
  (ra/cljs-repl))
```

Inside of the todomvc directory, run 
> lein run -m clojure.main --init script/figwheel.clj --repl
> (start)
> (repl)
The server should now be available under localhost:8081.

**Comment by simonmeister** [comment]
I am no expert, but the following should work:

Add

``` clojure
[figwheel-sidecar "0.5.0-SNAPSHOT" :scope "test"]
```

to :dependencies in project.clj.

Create a new file "figwheel.clj" inside of todomvc/script with the following contents:

``` clojure
(require
  '[figwheel-sidecar.repl-api :as ra]
  '[com.stuartsierra.component :as component]
  '[todomvc.system :as system])

(def figwheel-config
  {:figwheel-options {}
   :build-ids ["dev"]
   :all-builds
   [{:id "dev"
     :figwheel true
     :source-paths ["src/cljs"]
     :compiler {:main 'todomvc.core
                :asset-path "/js"
                :output-to "resources/public/js/app.js"
                :output-dir "resources/public/js"
                :optimizations :none
                :static-fns true
                :optimize-constants true
                :pretty-print true
                :externs ["src/js/externs.js"]
                :closure-defines '{goog.DEBUG true}
                :verbose true}}]})

(defrecord Figwheel []
  component/Lifecycle
  (start [config]
    (ra/start-figwheel! config)
    config)
  (stop [config]
    (ra/stop-figwheel!)
    config))

(def sys
  (atom
    (component/system-map
      :figwheel (map->Figwheel figwheel-config)
      :app-server (system/dev-system
                    {:db-uri   "datomic:mem://localhost:4334/todos"
                     :web-port 8081}))))

(defn start []
  (swap! sys component/start))

(defn stop []
  (swap! sys component/stop))

(defn reload []
  (stop)
  (start))

(defn repl []
  (ra/cljs-repl))
```

Inside of the todomvc directory, run

> lein run -m clojure.main script/build.clj
> lein run -m clojure.main --init script/figwheel.clj --repl
> (start)
> (repl)

The server should now be available under localhost:8081.

**Comment by hkjels** [comment]
I get messages with status `500` back from the server with failed assertions.

**Comment by ssaul** [comment]
@SMeister When I go to http://localhost:3449/, I get the following message.

![image](https://cloud.githubusercontent.com/assets/8105326/11918210/15f4b362-a6ed-11e5-82b4-35dbacb9d8b7.png)

When I go to http://localhost:3449/html/index.html, the screen is blank but the chrome developer tools shows some errors.

![image](https://cloud.githubusercontent.com/assets/8105326/11918211/3a25ce74-a6ed-11e5-82b7-178db23b8fd9.png)

When I move bower_components in the html folder (which is probably wrong but at this point I was just trying anything) then some styling works but the developer tools gave me some different errors.

![image](https://cloud.githubusercontent.com/assets/8105326/11918219/6b3a46e8-a6ed-11e5-9901-0a8af93b67e1.png)

Any help would be greatly appreciated.

**Comment by fillet54** [comment]
@hkjels The mutate functions return `:value` incorrectly. According to the QuickStart:

> Mutations should return a map for :value. This map can contain two keys - :keys and/or :tempids.

After that was fixed I was still getting `500 (java.lang.Exception: Not Supported: class <different classes>)`. It was not always the same class. Having `:action` return `nil` stopped that from happening although I'm not sure why. 

Heres an updated `'todo/update`

``` clojure
(defmethod mutatef 'todo/update
  [{:keys [conn]} k {:keys [db/id todo/completed todo/title]}]
   {:value {:keys [:todos/by-id id]}
   :action
   (fn []
     @(d/transact conn
        [(merge {:db/id id}
           (when (or (true? completed) (false? completed))
             {:todo/completed completed})
           (when title
             {:todo/title title}))])
     nil)})
```

Note that even after fixing the mutate functions it doesn't seem like the complete app is wired up. I guess it can be seen as a good exercise if you are just coming up to speed with om.next.

**Comment by hkjels** [comment]
Ahh, that explains it. I thought it was suppose to be a fully functioning app that you could draw inspiration from. That should be mentioned in the `Readme` I think.

**Comment by swannodette** [comment]
I believe @anmonteiro has addressed this stuff in his PR which I just merged.
